[project]
name = 'Blockchain-Based-Specialized-Equipment-Rental'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.equipment-registration]
path = 'contracts/equipment-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.renter-verification]
path = 'contracts/renter-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
